/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Janelas;

import Controlador.Controlador_Cliente;
import Controlador.Controlador_Produto;
import Controlador.Controlador_ProdutosVendasProdutos;
import Controlador.Controlador_Vendas;
import Controlador.Controlador_VendasCliente;
import Controlador.Controlador_VendasProdutos;
import Modelos.Modelo_Cliente;
import Modelos.Modelo_ProdutosVendasProdutos;
import Modelos.Modelo_Vendas;
import Modelos.Modelo_VendasCliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import ponto_venda.Modelo_Produto;

/**
 *
 * @author Faculdade
 */
public class Janela_UltimaVenda extends javax.swing.JDialog {

    ArrayList<Modelo_Produto> listaModeloProduto = new ArrayList<>();
    ArrayList<Modelo_VendasCliente> listaModelVendasClientes = new ArrayList<>();
    ArrayList<Modelo_Vendas> listaModeloVendas = new ArrayList<>();
    ArrayList<Modelo_Cliente> listaModeloCliente = new ArrayList<>();
    ArrayList<Modelo_ProdutosVendasProdutos> listaProdutosVendasProdutos = new ArrayList<>();
    Modelo_Cliente modeloCliente = new Modelo_Cliente();
    Modelo_Produto modeloProduto = new Modelo_Produto();
    Modelo_ProdutosVendasProdutos modeloProdutosVendasProdutos = new Modelo_ProdutosVendasProdutos();
    Controlador_Produto controladorProduto = new Controlador_Produto();
    Controlador_Cliente controladorCliente = new Controlador_Cliente();
    Controlador_VendasCliente controladorVendasCliente = new Controlador_VendasCliente();
    Controlador_Vendas controladorVendas = new Controlador_Vendas();
    Controlador_VendasProdutos controladorVendasProdutos = new Controlador_VendasProdutos();
    Controlador_ProdutosVendasProdutos controladorProdutosVendasProdutos = new Controlador_ProdutosVendasProdutos();

    /**
     * Creates new form Janela_UltimaVenda
     */
    public Janela_UltimaVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarVendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_vendas = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas Realizadas");

        jLabel1.setText("Pesquisar");

        table_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Cliente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_vendas);
        if (table_vendas.getColumnModel().getColumnCount() > 0) {
            table_vendas.getColumnModel().getColumn(0).setPreferredWidth(50);
            table_vendas.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find.png"))); // NOI18N
        btPesquisar.setText("Buscar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btExcluir))
                        .addGap(0, 538, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Deseja excluir a venda?", "Excluir Venda", dialogButton);
        if (dialogButton == JOptionPane.YES_OPTION) {
            int linha = table_vendas.getSelectedRow();
            int codigoVenda = (int) table_vendas.getValueAt(linha, 0);
            listaModeloProduto = new ArrayList<>();
            listaProdutosVendasProdutos = controladorProdutosVendasProdutos.getListaProdutosVendasProdutosControlador(codigoVenda);
            for (int i = 0; i < listaProdutosVendasProdutos.size(); i++) {
                modeloProduto = new Modelo_Produto();
                modeloProduto.setId(listaProdutosVendasProdutos.get(i).getModeloProdutos().getId());
                modeloProduto.setEstoque((int) (listaProdutosVendasProdutos.get(i).getModeloProdutos().getEstoque()
                        + listaProdutosVendasProdutos.get(i).getModeloVendasProdutos().getVendaProQuant()));
                listaModeloProduto.add(modeloProduto);
            }
            if (controladorProduto.alterarEstoqueProdutoControlador(listaModeloProduto)) {
                controladorVendasProdutos.excluirVendasProdutosController(codigoVenda);
                if (controladorVendas.excluirVendasController(codigoVenda)) {
                    JOptionPane.showMessageDialog(this, "Venda excluída com sucesso!", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                    this.carregarVendas();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir a venda!", "ERRO", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda!", "ERRO", JOptionPane.WARNING_MESSAGE);
            }
        if (dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.table_vendas.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.table_vendas.setRowSorter(classificador);
        String texto = txtPesquisar.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_UltimaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_UltimaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_UltimaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_UltimaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Janela_UltimaVenda dialog = new Janela_UltimaVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) table_vendas.getModel();
        listaModelVendasClientes = controladorVendasCliente.getListaVendasCliente();

        int cont = listaModelVendasClientes.size();
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModeloVendas().getIdVendas(),
                listaModelVendasClientes.get(i).getModeloClientes().getNomeCliente(),
                listaModelVendasClientes.get(i).getModeloVendas().getVendaDataVenda()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_vendas;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
