/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Janelas;

import Controlador.Controlador_FormaPagamento;
import Modelos.Modelo_FormaPagamento;
import java.text.DecimalFormat;
import java.util.ArrayList;
import utilidade.FormataPonto;

/**
 *
 * @author Faculdade
 */
public class Janela_Finalizar extends javax.swing.JDialog {

    ArrayList<Modelo_FormaPagamento> listaFormaPagamento = new ArrayList<>();
    Controlador_FormaPagamento controladorFormaPagamento = new Controlador_FormaPagamento();
    FormataPonto formatador = new FormataPonto();
    private float valorTotal;
    private float desconto;
    private float valorRecebido;
    private float troco;
    private String formaPagamento;
    private boolean pagamentoEfetuadoComSucesso;

    /**
     * Creates new form Finalizar
     */
    public Janela_Finalizar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaFormaPagamento();
        setLocationRelativeTo(null);
        pagamentoEfetuadoComSucesso = false;
        calcularPagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btFinalizar = new javax.swing.JButton();
        labelValorTotal = new javax.swing.JLabel();
        comboFinalizarForPag = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtFinalizarSubtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFinalizarDesconto = new javax.swing.JFormattedTextField();
        txtFinalizarRecebido = new javax.swing.JFormattedTextField();
        txtFinalizarTroco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Venda");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VALOR TOTAL A PAGAR");

        jLabel2.setText("Desconto R$");

        jLabel3.setText("Recebido R$");

        jLabel8.setText("Troco R$");

        btFinalizar.setText("Finalizar Venda");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        labelValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValorTotal.setText("0");

        jLabel10.setText("Forma de Pagamento");

        txtFinalizarSubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFinalizarSubtotal.setEnabled(false);

        jLabel11.setText("Subtotal");

        txtFinalizarDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFinalizarDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFinalizarDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFinalizarDescontoFocusLost(evt);
            }
        });

        txtFinalizarRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFinalizarRecebido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFinalizarRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFinalizarRecebidoFocusLost(evt);
            }
        });

        txtFinalizarTroco.setBackground(new java.awt.Color(255, 255, 204));
        txtFinalizarTroco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtFinalizarTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFinalizarTroco.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtFinalizarTroco.setEnabled(false);
        txtFinalizarTroco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFinalizarSubtotal)
                                    .addComponent(comboFinalizarForPag, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFinalizarDesconto)
                                    .addComponent(txtFinalizarRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFinalizarTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFinalizarForPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFinalizarSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFinalizarDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFinalizarRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFinalizarTroco, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        this.desconto = Float.parseFloat(this.txtFinalizarDesconto.getText());
        this.valorRecebido = Float.parseFloat(this.txtFinalizarRecebido.getText());
        this.troco = Float.parseFloat(this.txtFinalizarTroco.getText());
        this.valorTotal = Float.parseFloat(this.labelValorTotal.getText());
        this.formaPagamento = comboFinalizarForPag.getSelectedItem().toString();
        this.pagamentoEfetuadoComSucesso = true;
        dispose();
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void txtFinalizarDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFinalizarDescontoFocusLost
        //txtFinalizarDesconto.setText(String.valueOf(formatador.converteVirgulaparaPonto(txtFinalizarDesconto.getText())));
        calcularPagamento();
    }//GEN-LAST:event_txtFinalizarDescontoFocusLost

    private void txtFinalizarRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFinalizarRecebidoFocusLost
        //txtFinalizarRecebido.setText(String.valueOf(formatador.converteVirgulaparaPonto(txtFinalizarRecebido.getText())));
        calcularPagamento();
    }//GEN-LAST:event_txtFinalizarRecebidoFocusLost

    /**
     * FAZ O CÁLCULO FINAL DA VENDA
     */
    private void calcularPagamento() {
        float subTotal, desconto, recebido, valorPagar, troco;

        try {
            //formatador.converteVirgulaparaPonto(String.valueOf(subTotal));
            subTotal = Float.parseFloat(txtFinalizarSubtotal.getText());
        } catch (Exception e) {
            subTotal = 0;
        }

        try {
            //formatador.converteVirgulaparaPonto(String.valueOf(desconto));
            desconto = Float.parseFloat((txtFinalizarDesconto.getText()));
        } catch (Exception e) {
            desconto = 0;
            txtFinalizarDesconto.setText("0");
        }
        
        try {
            //formatador.converteVirgulaparaPonto(String.valueOf(recebido));
            recebido = Float.parseFloat(txtFinalizarRecebido.getText());
        } catch (Exception e) {
            recebido = 0;
            txtFinalizarRecebido.setText("0");
        }

        //calcular valor a pagar
        valorPagar = subTotal - desconto;
        //labelValorTotal.setText(arredondar(valorPagar));
        labelValorTotal.setText(String.valueOf(valorPagar));

        //calcular o troco
        troco = recebido - valorPagar;
        //txtFinalizarTroco.setText(arredondar(troco));
        txtFinalizarTroco.setText(String.valueOf(troco));
        //troco = Float.parseFloat(txtFinalizarTroco.getText());
    }
    
    public String arredondar(float pArredondar){
        DecimalFormat df = new DecimalFormat("#.00");
        return df.format(pArredondar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Finalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Janela_Finalizar dialog = new Janela_Finalizar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * PREENCHE O COMBOBOX COM AS FORMAS DE PAGAMENTO
     */
    private void listaFormaPagamento() {
        listaFormaPagamento = controladorFormaPagamento.getListaFormaPagamentoController();
        comboFinalizarForPag.removeAllItems();
        for (int i = 0; i < listaFormaPagamento.size(); i++) {
            comboFinalizarForPag.addItem(listaFormaPagamento.get(i).getDescricaoForPag());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizar;
    private javax.swing.JComboBox<String> comboFinalizarForPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JFormattedTextField txtFinalizarDesconto;
    private javax.swing.JFormattedTextField txtFinalizarRecebido;
    private javax.swing.JTextField txtFinalizarSubtotal;
    private javax.swing.JFormattedTextField txtFinalizarTroco;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the valorTotal
     */
    public float getValorTotal() {
        return valorTotal;
    }

    /**
     * @param valorTotal the valorTotal to set
     */
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

    /**
     * @return the desconto
     */
    public float getDesconto() {
        return desconto;
    }

    /**
     * @param desconto the desconto to set
     */
    public void setDesconto(float desconto) {
        this.desconto = desconto;
    }

    /**
     * @return the valorRecebido
     */
    public float getValorRecebido() {
        return valorRecebido;
    }

    /**
     * @param valorRecebido the valorRecebido to set
     */
    public void setValorRecebido(float valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    /**
     * @return the troco
     */
    public float getTroco() {
        return troco;
    }

    /**
     * @param troco the troco to set
     */
    public void setTroco(float troco) {
        this.troco = troco;
    }

    /**
     * @return the formaPagamento
     */
    public String getFormaPagamento() {
        return formaPagamento;
    }

    public void setTextFieldValorTotal() {
        this.txtFinalizarSubtotal.setText(this.valorTotal + "");
    }

    /**
     * @param formaPagamento the formaPagamento to set
     */
    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    /**
     * @return the pagamentoEfetuadoComSucesso
     */
    public boolean isPagamentoEfetuadoComSucesso() {
        return pagamentoEfetuadoComSucesso;
    }

    /**
     * @param pagamentoEfetuadoComSucesso the pagamentoEfetuadoComSucesso to set
     */
    public void setPagamentoEfetuadoComSucesso(boolean pagamentoEfetuadoComSucesso) {
        this.pagamentoEfetuadoComSucesso = pagamentoEfetuadoComSucesso;
    }
}
